server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local

  application:
    name: User-Service

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    database: postgresql
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true

  datasource:
    hikari:
      maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/ice_users
    username: postgres
    password: test12
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(I+PDk31WFTOU39AypeTrZFVbb8MSpV9oL9q2C3HGQD8/1+Wj7fVmMw==)
    password: ENC(TRk22TqlQbz1iTprwMnpiEMZLFAarFDjMf/iTDTnDCw=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000 # 10분

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.125.181.139:8761/eureka

greeting:
  message: Welcome to the Ice-Americano Page

secretKey: amazing
