server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  application:
    name: User-Service

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  #JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create # create or validate

    #배포 할 때는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password: 

  mail:
    host: smtp.gmail.com
    port: 587 #TLS : 587, SSL : 465
#    username: ENC(Z5N6xQWGf12Y0PVBB6EnVVVSjzhFG2msBboALjTUitSzYHoIpd0RSQ==)
    username:
#    password: ENC(P6Mn7j0vjT5fRUox4G69fauwhN2uoCpVJHL7ci5LIiM=)
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write timeout: 5000
    auth-code-expiration-millis: 600000 # 10분

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://13.125.181.139:8761/eureka

greeting:
  message: Welcome to the Studio-eye Page

secretKey: amazing