name: SonarQube Analysis

on:
  push:
    branches:
      - test

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarQube analysis
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_LOGIN }}
          

#      # gradlw 파일 권한 변경
#      - name: gradlew permission change
#        run: sudo chmod 755 gradlew
#
#      # Gralde 의 Scanner 발동, 위의 env 에서 선언한 환경변수와 함께 발동
#      - name: Sonaqube Analysis
#        run: ./gradlew test sonarqube
#          -Dsonar.host.url=${{ env.SONARQUBE_URL }}
#          -Dsonar.projectKey=${{ env.SONARQUBE_PROJECT_KEY }}
#          -Dsonar.projectName=${{ env.SONARQUBE_PROJECT_KEY }}-${{ env.PR_NUMBER }}
#          -Dsonar.login=${{ env.SONARQUBE_TOKEN }}
